### ISSUE TITLE
Client Interface Plugin installed but unable to login

### ISSUE THREAD

**Issue by brashquido** [alberto234/wurrd-client-interface-plugin#5]
Hi There,

I have a fresh install of Mibew 2.1 and have created myself an operator account. In installed the AuthAPI (0.1.3) and ClientInterface (1.0.3) plugins without a hitch and they are listed in the Mibew admin panel as in a working state. There are no other plugins enabled.

I installed the Android Wurrd app on my LG G3, entered the URL of my Mibew install and put in my new operator account. I am getting a message saying "The Wurrd Client Interface plugin may not be installed on your server".  

Only other issue I've had was during Mibew installation where I had to set the caching type to none as for some reason file_system was not working on my Windows 2012 / IIS 8 server.

Any ideas?

**Comment by brashquido** [comment]
Should point out that I am able to log into my Mibew install with this new operator account just fine. I have granted it all permissions apart from the administrative ones.

**Comment by alberto234** [comment]
Hello and sorry for the delayed response.

I have received the "Can't login" complain several times and it is a pain trying to identify where things are going wrong given that everyone's setup is slightly different. I have spent a few hours putting a script together to help some basic testing. 
- Drop the attached file at the root of your chat server (or anywhere, doesn't matter).
- Point your browser to the location of the file (e.g. http://wurrdapp.com/mibew1/testwurrd.php)
- Fill in the information click submit and let me know where it fails.

If you get past the point where it displays your server info, then at least some basic stuff is working. You may be dealing with a situation where your server filters out PUT and DELETE requests. Check out this issue to enable the use of POST, then run the test again with POST being checked.

[testwurrd.php.zip](https://github.com/alberto234/wurrd-client-interface-plugin/files/267402/testwurrd.php.zip)

**Comment by brashquido** [comment]
Thanks for the reply.

As soon as you mentioned HTTP request types I knew where to look, didn't even end up downloading your file. As a security measure I only had HTTP GET, HEAD & POST verbs enabled on my server. I opened that to all verbs and I am now able to login without issue. No wonder nothing was hitting my PHP log, IIS was configured to filter them out. 

Perhaps a FAQ with all required HTTP verbs for Wurrd? 

Thanks so much for your help and for developing this app!

**Comment by waldierrafael** [comment]
Hello, I have a problem installing the wurrd plugin in mibew. When I activate it I have the following message. [b]Plugin "Wurrd: AuthAPI" can not be enabled.[/b] I have modified the config file as some tutorials indicate on the internet and the problem persists. Mibew works fine, only the problem is to activate the wurrd plugin.

My config file looks like this:
plugins:
  "Wurrd:AuthAPI":
    client_id: TEST_CLIENT_ID
  "Wurrd:ClientInterface":
    use_http_post: false

Am I making a mistake?

I've done a wurrd test and it reports:
Testing in progress...

Error getting server info! Returned message: 
Failed to get server info. Stopping tests here
Testing complete

Click the back button to run another test
